### ISSUE TITLE
BlockBuilder should accept Function<TileEntityType<T>, T> for .tileEntity()

### ISSUE THREAD

**Issue by Drullkus** [tterrag1098/Registrate#4]
🙏 pls

Currently `.tileEntity` in `BlockBuilder` only accepts `NonNullSupplier<? extends TileEntity>`, only allowing new parameter-less instances of a TE. This introduces a chicken-before-egg type problem where to write a new `TileEntity`, I'd have to get the `TileEntityType` instance. Unfortunately that's shoved away in the `BlockBuilder` which only returns `Block`.

**Comment by tterrag1098** [comment]
This won't work, since the block still needs to have a static ref to the TileEntityType. Open to suggestions, but for now I recommend using the new (`RegistryEntry#getSibling`)[https://ci.tterrag.com/job/Registrate/job/1.14/javadoc/com/tterrag/registrate/util/RegistryEntry.html#getSibling-java.lang.Class-] to easily obtain other entries of the same name.

```java
public static final RegistryObject<Block> MY_BLOCK = REGISTRATE.block(...).register();
public static final RegistryObject<TileEntityType<?>> MY_BLOCK_TE = MY_BLOCK.getSibling(TileEntityType.class);
```
